### ISSUE TITLE
slideshow support

### ISSUE THREAD

**Issue by basco** [freshollie/monkeyboard-radio-android#11]
I see the new monkeyboard has slideshow support.
Would it be possible to implement this feature in this app?

thanks,

**Comment by freshollie** [comment]
I have looked into this before I found that even using their software I could not get a slideshow image. This may have been because I was living in the U.K.

I am currently living in Germany and I will look into this if I can get my board to produce a slideshow with their software.

**Comment by freshollie** [comment]
Good news! This works in germany! I will hopefully translate their slideshow sourcecode into java and maybe get this working on android. No promises though!

**Comment by basco** [comment]
Great!!

Op 24 sep. 2017 18:39 schreef "Oliver Bell" <notifications@github.com>:

**Comment by freshollie** [comment]
Hey this is ready for testing! Checkout https://github.com/freshollie/monkeyboard-radio-android/tree/development for the development APK and see what you think.

Note: Your country needs to support slideshows, and there seems to be a bug when fetching slideshow data which causes the images to sometimes take a while to show up. 

Please let me know how it goes before I merge this into master!

**Comment by freshollie** [comment]
Made another few updates tonight. If you have already downloaded the last version I urge you to try this version.
