### ISSUE TITLE
Heavy load in new version

### ISSUE THREAD

**Issue by tgghtp** [freshollie/monkeyboard-radio-android#15]
The new version has heavy cpu load, 122% on an octacore (Odroid XU4)
Old version (# BETA 1.2.2) has 25-40%.

  PID USER     PR  NI VIRT  RES  SHR S[%CPU] %MEM     TIME+ ARGS
 4648 u0_a78   10 -10 997M  81M  50M S 29.3   4.0   9:36.63 com.freshollie.monkeyboard.keystoneradio

**Comment by freshollie** [comment]
Very, weird. I have not changed anything between the 2 versions which could cause this. Can you show any more tests of this? Is it's average CPU usage really that high?

**Comment by freshollie** [comment]
https://github.com/freshollie/monkeyboard-radio-android/compare/beta-v2.1.2...beta-v2.1.3

I will look more into this tomorrow.

**Comment by freshollie** [comment]
OK, this is going to me my fault. The main thread which reads data from the board runs very quickly and so potentially eats up the CPU.

**Comment by freshollie** [comment]
Potentially fixed in [v2.1.4-beta](https://github.com/freshollie/monkeyboard-radio-android/releases/tag/v2.1.4-beta)
