### ISSUE TITLE
Give permanent usb permission 

### ISSUE THREAD

**Issue by Bigmanni** [freshollie/monkeyboard-radio-android#17]
Hi,
Is it possible to grant a permanent permission for USB access.
After each reconnect, ask android for permission.
It is not possible to give it permanently.
Apparently, something has to be changed in the usb driver.

Thanks for this cool software!

**Comment by freshollie** [comment]
No problem!

Unfortunately, this is an issue with Android itself. I *must* request permission every time the USB device is reconnected.

[To quote another one of my repositories](https://github.com/freshollie/UsbGps4Droid)

>  ### USB Permissions Popup
> **Unless your ROM is modified then Android will ask permission to use your USB GPS device 
> everytime you reconnect it**
> 
> If your device is rooted, then you can follow [this tutorial](https://stackoverflow.com/a/30563253/1741602) 
> in order to surpress the USB permission popup system wide and grant permission everytime automatically.
> 
> If your device is not rooted, then there is nothing I can do. This is unfortunately a limitation of 
> the android operating system. If this is for an embedded system I highly recommend rooting the device
> and following the tutorial.
> 


Sorry!
