### ISSUE TITLE
Clicking on + icon crashes the app

### ISSUE THREAD

**Issue by neupanedipen** [freshollie/monkeyboard-radio-android#18]
#### Expected behavior<br>
I should be able to add channels on clicking the + icon.<br>
#### Actual behavior<br>
But the app crashes on clicking the + icon after launching the app.<br>
#### How to reproduce<br>
1. Install the app from releases page.<br>
2. Launch the app.<br>
3. Click on + icon.<br>
The app crashes.<br>
* App Version: 2.1.4<br>
* Device: Samsung Galaxy J5<br>
* Operating System: Android 6.0.1<br>
#### Recording Of The Bug<br>
https://youtu.be/Lj7tINMNGns

**Comment by freshollie** [comment]
This bug is caused when the board is not connected and you try to "save" the channel you are currently on. I can fix the bug, but I'm not sure what you expected from clicking "save" before the board was actually connected.
